# Generated by Django 3.0.1 on 2020-06-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200623_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
