# Generated by Django 4.0.4 on 2022-05-06 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200623_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_no',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=9860933006, max_length=15, validators=[django.core.validators.RegexValidator(message='Incorrect Phone Number format! Phone number must be of format +977-01XXXXXX or +977-98XXXXXXXX', regex='(?:\\+977[- ])?\\d{2}-?\\d{7,8}')]),
            preserve_default=False,
        ),
    ]
