# Generated by Django 3.0.1 on 2020-06-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_speak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speak',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaks', to='store.Book'),
        ),
    ]
