# Generated by Django 3.0.1 on 2020-06-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200624_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
